# _config.yml

# Use the remote Agency Jekyll theme from GitHub
remote_theme: raviriley/agency-jekyll-theme

# Site URL settings
# If hosting on a custom domain, set url to "https://www.example.com", otherwise keep ""
url: ""
# If you're deploying to a subfolder, e.g. "example.com/subsite", set baseurl: "/subsite"
baseurl: ""

# Site basics
title: "Gap Tap"
email: "support@gap-tap.com"  # The email used by contact forms
description: "Close floor gaps in laminate, vinyl, or wood quickly with Gap Tap!"
author: "Circle Solutions LLC"

# Choose the default locale for the site
locale: "en-US"

# Google Analytics (optional)
analytics:
  google: ""  # e.g. UA-XXXXXX-1 or G-XXXXXXXXXX

# If you need to prevent spam via Formspree ID-based forms:
# formspree_form_path: "f/your_form_id"

# Jekyll build settings
#collections:
 # portfolio:

markdown: kramdown

plugins:
  - jekyll-remote-theme
